// This file is @generated by prost-build.
/// Module is the config object for the module.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    /// authority defines the custom module authority. If not set, defaults to the governance module.
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
}
impl ::prost::Name for Module {
    const NAME: &'static str = "Module";
    const PACKAGE: &'static str = "pocket.proof.module";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.proof.module.Module".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.proof.module.Module".into()
    }
}
