// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Gateway {
    /// The Bech32 address of the gateway
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// The total amount of uPOKT the gateway has staked
    #[prost(message, optional, tag = "2")]
    pub stake: ::core::option::Option<super::super::cosmos::base::v1beta1::Coin>,
    /// Session end height at which the gateway initiated unstaking (0 if not unstaking)
    #[prost(uint64, tag = "3")]
    pub unstake_session_end_height: u64,
}
impl ::prost::Name for Gateway {
    const NAME: &'static str = "Gateway";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.Gateway".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.Gateway".into()
    }
}
/// EventGatewayStaked is emitted when a gateway is staked or up-staked.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventGatewayStaked {
    /// The gateway that has been staked.
    #[prost(message, optional, tag = "1")]
    pub gateway: ::core::option::Option<Gateway>,
    /// The end height of the session in which gateway was staked.
    #[prost(int64, tag = "2")]
    pub session_end_height: i64,
}
impl ::prost::Name for EventGatewayStaked {
    const NAME: &'static str = "EventGatewayStaked";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.EventGatewayStaked".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.EventGatewayStaked".into()
    }
}
/// EventGatewayUnbondingBegin is emitted when a gateway begins unbonding.
/// It is triggered by the commitment of an unstake gateway message.
/// This event signals that a gateway has begun unbonding.
/// The unbonding period is determined by the shared param gateway_unbonding_period_sessions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventGatewayUnbondingBegin {
    #[prost(message, optional, tag = "1")]
    pub gateway: ::core::option::Option<Gateway>,
    /// The end height of the session in which the unbonding began.
    #[prost(int64, tag = "3")]
    pub session_end_height: i64,
    /// The height at which gateway unbonding will end.
    #[prost(int64, tag = "4")]
    pub unbonding_end_height: i64,
}
impl ::prost::Name for EventGatewayUnbondingBegin {
    const NAME: &'static str = "EventGatewayUnbondingBegin";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.EventGatewayUnbondingBegin".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.EventGatewayUnbondingBegin".into()
    }
}
/// EventGatewayUnbondingEnd is emitted when a gateway has completed unbonding.
/// The unbonding period is determined by the shared param gateway_unbonding_period_sessions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventGatewayUnbondingEnd {
    /// The gateway that has completed unbonding.
    #[prost(message, optional, tag = "1")]
    pub gateway: ::core::option::Option<Gateway>,
    /// The end height of the session in which the unbonding began.
    #[prost(int64, tag = "3")]
    pub session_end_height: i64,
    /// The height at which gateway unbonding will end.
    #[prost(int64, tag = "4")]
    pub unbonding_end_height: i64,
}
impl ::prost::Name for EventGatewayUnbondingEnd {
    const NAME: &'static str = "EventGatewayUnbondingEnd";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.EventGatewayUnbondingEnd".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.EventGatewayUnbondingEnd".into()
    }
}
/// EventGatewayUnbondingCanceled is emitted when a gateway which was unbonding
/// successfully (re-)stakes before the unbonding period has elapsed.
/// An EventGatewayStaked event will also be emitted immediately after this event.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventGatewayUnbondingCanceled {
    #[prost(message, optional, tag = "1")]
    pub gateway: ::core::option::Option<Gateway>,
    /// The end height of the session in which the unbonding was canceled.
    #[prost(int64, tag = "2")]
    pub session_end_height: i64,
}
impl ::prost::Name for EventGatewayUnbondingCanceled {
    const NAME: &'static str = "EventGatewayUnbondingCanceled";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.EventGatewayUnbondingCanceled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.EventGatewayUnbondingCanceled".into()
    }
}
/// Params defines the parameters for the module.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Params {
    /// min_stake is the minimum amount of uPOKT that a gateway must stake.
    #[prost(message, optional, tag = "1")]
    pub min_stake: ::core::option::Option<super::super::cosmos::base::v1beta1::Coin>,
}
impl ::prost::Name for Params {
    const NAME: &'static str = "Params";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.Params".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.Params".into()
    }
}
/// GenesisState defines the gateway module's genesis state.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    /// params defines all the parameters of the module.
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
    #[prost(message, repeated, tag = "2")]
    pub gateway_list: ::prost::alloc::vec::Vec<Gateway>,
}
impl ::prost::Name for GenesisState {
    const NAME: &'static str = "GenesisState";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.GenesisState".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.GenesisState".into()
    }
}
/// QueryParamsRequest is request type for the Query/Params RPC method.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {}
impl ::prost::Name for QueryParamsRequest {
    const NAME: &'static str = "QueryParamsRequest";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.QueryParamsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.QueryParamsRequest".into()
    }
}
/// QueryParamsResponse is response type for the Query/Params RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    /// params holds all the parameters of this module.
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
}
impl ::prost::Name for QueryParamsResponse {
    const NAME: &'static str = "QueryParamsResponse";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.QueryParamsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.QueryParamsResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryGetGatewayRequest {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryGetGatewayRequest {
    const NAME: &'static str = "QueryGetGatewayRequest";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.QueryGetGatewayRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.QueryGetGatewayRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryGetGatewayResponse {
    #[prost(message, optional, tag = "1")]
    pub gateway: ::core::option::Option<Gateway>,
}
impl ::prost::Name for QueryGetGatewayResponse {
    const NAME: &'static str = "QueryGetGatewayResponse";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.QueryGetGatewayResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.QueryGetGatewayResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryAllGatewaysRequest {
    #[prost(message, optional, tag = "1")]
    pub pagination: ::core::option::Option<
        super::super::cosmos::base::query::v1beta1::PageRequest,
    >,
}
impl ::prost::Name for QueryAllGatewaysRequest {
    const NAME: &'static str = "QueryAllGatewaysRequest";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.QueryAllGatewaysRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.QueryAllGatewaysRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryAllGatewaysResponse {
    #[prost(message, repeated, tag = "1")]
    pub gateways: ::prost::alloc::vec::Vec<Gateway>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::cosmos::base::query::v1beta1::PageResponse,
    >,
}
impl ::prost::Name for QueryAllGatewaysResponse {
    const NAME: &'static str = "QueryAllGatewaysResponse";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.QueryAllGatewaysResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.QueryAllGatewaysResponse".into()
    }
}
/// Generated client implementations.
pub mod query_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Query defines the gRPC querier service.
    #[derive(Debug, Clone)]
    pub struct QueryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl QueryClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QueryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            QueryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Parameters queries the parameters of the module.
        pub async fn params(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryParamsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryParamsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.gateway.Query/Params",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.gateway.Query", "Params"));
            self.inner.unary(req, path, codec).await
        }
        /// Queries a list of Gateway items.
        pub async fn gateway(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryGetGatewayRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryGetGatewayResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.gateway.Query/Gateway",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.gateway.Query", "Gateway"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn all_gateways(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryAllGatewaysRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryAllGatewaysResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.gateway.Query/AllGateways",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.gateway.Query", "AllGateways"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// MsgUpdateParams is the Msg/UpdateParams request type.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateParams {
    /// authority is the address that controls the module (defaults to x/gov unless overwritten).
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
    /// params defines the x/gateway parameters to update.
    /// NOTE: All parameters must be supplied.
    #[prost(message, optional, tag = "2")]
    pub params: ::core::option::Option<Params>,
}
impl ::prost::Name for MsgUpdateParams {
    const NAME: &'static str = "MsgUpdateParams";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.MsgUpdateParams".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.MsgUpdateParams".into()
    }
}
/// MsgUpdateParamsResponse defines the response structure for executing a
/// MsgUpdateParams message.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateParamsResponse {}
impl ::prost::Name for MsgUpdateParamsResponse {
    const NAME: &'static str = "MsgUpdateParamsResponse";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.MsgUpdateParamsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.MsgUpdateParamsResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgStakeGateway {
    /// The Bech32 address of the gateway
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// The total amount of uPOKT the gateway is staking. Must be ≥ to the current amount that the gateway has staked (if any)
    #[prost(message, optional, tag = "2")]
    pub stake: ::core::option::Option<super::super::cosmos::base::v1beta1::Coin>,
}
impl ::prost::Name for MsgStakeGateway {
    const NAME: &'static str = "MsgStakeGateway";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.MsgStakeGateway".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.MsgStakeGateway".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgStakeGatewayResponse {}
impl ::prost::Name for MsgStakeGatewayResponse {
    const NAME: &'static str = "MsgStakeGatewayResponse";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.MsgStakeGatewayResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.MsgStakeGatewayResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUnstakeGateway {
    /// The Bech32 address of the gateway
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
}
impl ::prost::Name for MsgUnstakeGateway {
    const NAME: &'static str = "MsgUnstakeGateway";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.MsgUnstakeGateway".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.MsgUnstakeGateway".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUnstakeGatewayResponse {}
impl ::prost::Name for MsgUnstakeGatewayResponse {
    const NAME: &'static str = "MsgUnstakeGatewayResponse";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.MsgUnstakeGatewayResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.MsgUnstakeGatewayResponse".into()
    }
}
/// MsgUpdateParam is the Msg/UpdateParam request type to update a single param.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateParam {
    /// authority is the address that controls the module (defaults to x/gov unless overwritten).
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(oneof = "msg_update_param::AsType", tags = "3")]
    pub as_type: ::core::option::Option<msg_update_param::AsType>,
}
/// Nested message and enum types in `MsgUpdateParam`.
pub mod msg_update_param {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum AsType {
        #[prost(message, tag = "3")]
        AsCoin(super::super::super::cosmos::base::v1beta1::Coin),
    }
}
impl ::prost::Name for MsgUpdateParam {
    const NAME: &'static str = "MsgUpdateParam";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.MsgUpdateParam".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.MsgUpdateParam".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateParamResponse {}
impl ::prost::Name for MsgUpdateParamResponse {
    const NAME: &'static str = "MsgUpdateParamResponse";
    const PACKAGE: &'static str = "pocket.gateway";
    fn full_name() -> ::prost::alloc::string::String {
        "pocket.gateway.MsgUpdateParamResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/pocket.gateway.MsgUpdateParamResponse".into()
    }
}
/// Generated client implementations.
pub mod msg_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Msg defines the Msg service.
    #[derive(Debug, Clone)]
    pub struct MsgClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MsgClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MsgClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MsgClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MsgClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// UpdateParams defines a (governance) operation for updating the module
        /// parameters. The authority defaults to the x/gov module account.
        pub async fn update_params(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUpdateParams>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateParamsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.gateway.Msg/UpdateParams",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.gateway.Msg", "UpdateParams"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stake_gateway(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgStakeGateway>,
        ) -> std::result::Result<
            tonic::Response<super::MsgStakeGatewayResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.gateway.Msg/StakeGateway",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.gateway.Msg", "StakeGateway"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn unstake_gateway(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUnstakeGateway>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUnstakeGatewayResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.gateway.Msg/UnstakeGateway",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.gateway.Msg", "UnstakeGateway"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_param(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUpdateParam>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateParamResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.gateway.Msg/UpdateParam",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.gateway.Msg", "UpdateParam"));
            self.inner.unary(req, path, codec).await
        }
    }
}
