// This file is @generated by prost-build.
/// ClaimSettlementResult holds the result of a single claim settlement: mint, burn, and transfer operations.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimSettlementResult {
    #[prost(message, optional, tag = "1")]
    pub claim: ::core::option::Option<super::proof::Claim>,
    #[prost(message, repeated, tag = "2")]
    pub mints: ::prost::alloc::vec::Vec<MintBurnOp>,
    #[prost(message, repeated, tag = "3")]
    pub burns: ::prost::alloc::vec::Vec<MintBurnOp>,
    #[prost(message, repeated, tag = "4")]
    pub mod_to_mod_transfers: ::prost::alloc::vec::Vec<ModToModTransfer>,
    #[prost(message, repeated, tag = "5")]
    pub mod_to_acct_transfers: ::prost::alloc::vec::Vec<ModToAcctTransfer>,
}
/// MintBurnOp holds the parameters of a single mint or burn operation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MintBurnOp {
    #[prost(enumeration = "SettlementOpReason", tag = "1")]
    pub op_reason: i32,
    #[prost(string, tag = "2")]
    pub destination_module: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub coin: ::core::option::Option<super::super::cosmos::base::v1beta1::Coin>,
}
/// ModToAcctTransfer holds the parameters of a single module to account transfer operation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModToAcctTransfer {
    #[prost(enumeration = "SettlementOpReason", tag = "1")]
    pub op_reason: i32,
    #[prost(string, tag = "2")]
    pub sender_module: ::prost::alloc::string::String,
    /// bech32 address
    #[prost(string, tag = "3")]
    pub recipient_address: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub coin: ::core::option::Option<super::super::cosmos::base::v1beta1::Coin>,
}
/// ModToModTransfer holds the parameters of a single module to module transfer operation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModToModTransfer {
    #[prost(enumeration = "SettlementOpReason", tag = "1")]
    pub op_reason: i32,
    #[prost(string, tag = "2")]
    pub sender_module: ::prost::alloc::string::String,
    /// This the semantic module named that can be found by searching for "ModuleName =" in the codebase
    #[prost(string, tag = "3")]
    pub recipient_module: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub coin: ::core::option::Option<super::super::cosmos::base::v1beta1::Coin>,
}
/// SettlementOpReason is a distinct, tlm-specific causal reason for a given operation.
///
/// Next free index: 25
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SettlementOpReason {
    /// UNSPECIFIED is the default value for SettlementOpReason
    /// It is used as a field type for objects which need to distinguish whether a SettlementOpReason has been specified it or not.
    Unspecified = 0,
    /// All TLMs: Penalization: Slash, burn, etc...
    UnspecifiedTlmSupplierSlashModuleTransfer = 11,
    UnspecifiedTlmSupplierSlashStakeBurn = 12,
    /// MintEqualsBurnTlm: Value transfer (credit/debit aka mint/burn)
    TlmRelayBurnEqualsMintSupplierStakeMint = 1,
    TlmRelayBurnEqualsMintApplicationStakeBurn = 2,
    TlmRelayBurnEqualsMintTokenomicsClaimDistributionMint = 19,
    /// MintEqualsBurnTlm: Reward distribution
    TlmRelayBurnEqualsMintSupplierShareholderRewardDistribution = 4,
    TlmRelayBurnEqualsMintDaoRewardDistribution = 15,
    TlmRelayBurnEqualsMintSourceOwnerRewardDistribution = 17,
    TlmRelayBurnEqualsMintApplicationRewardDistribution = 18,
    TlmRelayBurnEqualsMintValidatorRewardDistribution = 20,
    TlmRelayBurnEqualsMintDelegatorRewardDistribution = 23,
    /// GlobalMintTLM: Inflation
    TlmGlobalMintInflation = 3,
    /// GlobalMintTLM: Reward distribution
    TlmGlobalMintDaoRewardDistribution = 5,
    TlmGlobalMintSupplierShareholderRewardDistribution = 7,
    TlmGlobalMintSourceOwnerRewardDistribution = 8,
    TlmGlobalMintApplicationRewardDistribution = 9,
    TlmGlobalMintValidatorRewardDistribution = 21,
    TlmGlobalMintDelegatorRewardDistribution = 24,
    /// GlobalMintTLM: Self-servicing mitigation
    TlmGlobalMintReimbursementRequestEscrowDaoTransfer = 10,
    /// GlobalMintTLM: Module accounting
    TlmGlobalMintSupplierShareholderRewardModuleTransfer = 13,
    TlmGlobalMintReimbursementRequestEscrowModuleTransfer = 14,
}
impl SettlementOpReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "UNSPECIFIED",
            Self::UnspecifiedTlmSupplierSlashModuleTransfer => {
                "UNSPECIFIED_TLM_SUPPLIER_SLASH_MODULE_TRANSFER"
            }
            Self::UnspecifiedTlmSupplierSlashStakeBurn => {
                "UNSPECIFIED_TLM_SUPPLIER_SLASH_STAKE_BURN"
            }
            Self::TlmRelayBurnEqualsMintSupplierStakeMint => {
                "TLM_RELAY_BURN_EQUALS_MINT_SUPPLIER_STAKE_MINT"
            }
            Self::TlmRelayBurnEqualsMintApplicationStakeBurn => {
                "TLM_RELAY_BURN_EQUALS_MINT_APPLICATION_STAKE_BURN"
            }
            Self::TlmRelayBurnEqualsMintTokenomicsClaimDistributionMint => {
                "TLM_RELAY_BURN_EQUALS_MINT_TOKENOMICS_CLAIM_DISTRIBUTION_MINT"
            }
            Self::TlmRelayBurnEqualsMintSupplierShareholderRewardDistribution => {
                "TLM_RELAY_BURN_EQUALS_MINT_SUPPLIER_SHAREHOLDER_REWARD_DISTRIBUTION"
            }
            Self::TlmRelayBurnEqualsMintDaoRewardDistribution => {
                "TLM_RELAY_BURN_EQUALS_MINT_DAO_REWARD_DISTRIBUTION"
            }
            Self::TlmRelayBurnEqualsMintSourceOwnerRewardDistribution => {
                "TLM_RELAY_BURN_EQUALS_MINT_SOURCE_OWNER_REWARD_DISTRIBUTION"
            }
            Self::TlmRelayBurnEqualsMintApplicationRewardDistribution => {
                "TLM_RELAY_BURN_EQUALS_MINT_APPLICATION_REWARD_DISTRIBUTION"
            }
            Self::TlmRelayBurnEqualsMintValidatorRewardDistribution => {
                "TLM_RELAY_BURN_EQUALS_MINT_VALIDATOR_REWARD_DISTRIBUTION"
            }
            Self::TlmRelayBurnEqualsMintDelegatorRewardDistribution => {
                "TLM_RELAY_BURN_EQUALS_MINT_DELEGATOR_REWARD_DISTRIBUTION"
            }
            Self::TlmGlobalMintInflation => "TLM_GLOBAL_MINT_INFLATION",
            Self::TlmGlobalMintDaoRewardDistribution => {
                "TLM_GLOBAL_MINT_DAO_REWARD_DISTRIBUTION"
            }
            Self::TlmGlobalMintSupplierShareholderRewardDistribution => {
                "TLM_GLOBAL_MINT_SUPPLIER_SHAREHOLDER_REWARD_DISTRIBUTION"
            }
            Self::TlmGlobalMintSourceOwnerRewardDistribution => {
                "TLM_GLOBAL_MINT_SOURCE_OWNER_REWARD_DISTRIBUTION"
            }
            Self::TlmGlobalMintApplicationRewardDistribution => {
                "TLM_GLOBAL_MINT_APPLICATION_REWARD_DISTRIBUTION"
            }
            Self::TlmGlobalMintValidatorRewardDistribution => {
                "TLM_GLOBAL_MINT_VALIDATOR_REWARD_DISTRIBUTION"
            }
            Self::TlmGlobalMintDelegatorRewardDistribution => {
                "TLM_GLOBAL_MINT_DELEGATOR_REWARD_DISTRIBUTION"
            }
            Self::TlmGlobalMintReimbursementRequestEscrowDaoTransfer => {
                "TLM_GLOBAL_MINT_REIMBURSEMENT_REQUEST_ESCROW_DAO_TRANSFER"
            }
            Self::TlmGlobalMintSupplierShareholderRewardModuleTransfer => {
                "TLM_GLOBAL_MINT_SUPPLIER_SHAREHOLDER_REWARD_MODULE_TRANSFER"
            }
            Self::TlmGlobalMintReimbursementRequestEscrowModuleTransfer => {
                "TLM_GLOBAL_MINT_REIMBURSEMENT_REQUEST_ESCROW_MODULE_TRANSFER"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSPECIFIED" => Some(Self::Unspecified),
            "UNSPECIFIED_TLM_SUPPLIER_SLASH_MODULE_TRANSFER" => {
                Some(Self::UnspecifiedTlmSupplierSlashModuleTransfer)
            }
            "UNSPECIFIED_TLM_SUPPLIER_SLASH_STAKE_BURN" => {
                Some(Self::UnspecifiedTlmSupplierSlashStakeBurn)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_SUPPLIER_STAKE_MINT" => {
                Some(Self::TlmRelayBurnEqualsMintSupplierStakeMint)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_APPLICATION_STAKE_BURN" => {
                Some(Self::TlmRelayBurnEqualsMintApplicationStakeBurn)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_TOKENOMICS_CLAIM_DISTRIBUTION_MINT" => {
                Some(Self::TlmRelayBurnEqualsMintTokenomicsClaimDistributionMint)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_SUPPLIER_SHAREHOLDER_REWARD_DISTRIBUTION" => {
                Some(Self::TlmRelayBurnEqualsMintSupplierShareholderRewardDistribution)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_DAO_REWARD_DISTRIBUTION" => {
                Some(Self::TlmRelayBurnEqualsMintDaoRewardDistribution)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_SOURCE_OWNER_REWARD_DISTRIBUTION" => {
                Some(Self::TlmRelayBurnEqualsMintSourceOwnerRewardDistribution)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_APPLICATION_REWARD_DISTRIBUTION" => {
                Some(Self::TlmRelayBurnEqualsMintApplicationRewardDistribution)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_VALIDATOR_REWARD_DISTRIBUTION" => {
                Some(Self::TlmRelayBurnEqualsMintValidatorRewardDistribution)
            }
            "TLM_RELAY_BURN_EQUALS_MINT_DELEGATOR_REWARD_DISTRIBUTION" => {
                Some(Self::TlmRelayBurnEqualsMintDelegatorRewardDistribution)
            }
            "TLM_GLOBAL_MINT_INFLATION" => Some(Self::TlmGlobalMintInflation),
            "TLM_GLOBAL_MINT_DAO_REWARD_DISTRIBUTION" => {
                Some(Self::TlmGlobalMintDaoRewardDistribution)
            }
            "TLM_GLOBAL_MINT_SUPPLIER_SHAREHOLDER_REWARD_DISTRIBUTION" => {
                Some(Self::TlmGlobalMintSupplierShareholderRewardDistribution)
            }
            "TLM_GLOBAL_MINT_SOURCE_OWNER_REWARD_DISTRIBUTION" => {
                Some(Self::TlmGlobalMintSourceOwnerRewardDistribution)
            }
            "TLM_GLOBAL_MINT_APPLICATION_REWARD_DISTRIBUTION" => {
                Some(Self::TlmGlobalMintApplicationRewardDistribution)
            }
            "TLM_GLOBAL_MINT_VALIDATOR_REWARD_DISTRIBUTION" => {
                Some(Self::TlmGlobalMintValidatorRewardDistribution)
            }
            "TLM_GLOBAL_MINT_DELEGATOR_REWARD_DISTRIBUTION" => {
                Some(Self::TlmGlobalMintDelegatorRewardDistribution)
            }
            "TLM_GLOBAL_MINT_REIMBURSEMENT_REQUEST_ESCROW_DAO_TRANSFER" => {
                Some(Self::TlmGlobalMintReimbursementRequestEscrowDaoTransfer)
            }
            "TLM_GLOBAL_MINT_SUPPLIER_SHAREHOLDER_REWARD_MODULE_TRANSFER" => {
                Some(Self::TlmGlobalMintSupplierShareholderRewardModuleTransfer)
            }
            "TLM_GLOBAL_MINT_REIMBURSEMENT_REQUEST_ESCROW_MODULE_TRANSFER" => {
                Some(Self::TlmGlobalMintReimbursementRequestEscrowModuleTransfer)
            }
            _ => None,
        }
    }
}
/// EventClaimExpired is emitted during settlement when a claim expires.
/// This is likely the result of a claim requiring an onchain proof not being submitted.
/// The claim cannot be settled, leading to that work never being rewarded.
///
/// Next index: 13
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventClaimExpired {
    /// The reason why the claim expired, leading to a Supplier being penalized (i.e. burn).
    #[prost(enumeration = "ClaimExpirationReason", tag = "2")]
    pub expiration_reason: i32,
    /// Number of relays claimed to be in the session tree.
    #[prost(uint64, tag = "3")]
    pub num_relays: u64,
    /// Number of compute units claimed in the session tree.
    /// It is a function of the number of relays in the session tree and onchain parameters.
    #[prost(uint64, tag = "4")]
    pub num_claimed_compute_units: u64,
    /// Number of total estimated compute units of work done.
    /// It is a function of the number of claimed compute units and the relay difficulty multiplier.
    #[prost(uint64, tag = "5")]
    pub num_estimated_compute_units: u64,
    /// The amount of uPOKT claimed for the work done.
    /// It is a function of the number of estimated compute units and the compute units to token multiplier.
    #[prost(string, tag = "7")]
    pub claimed_upokt: ::prost::alloc::string::String,
    /// The Service ID to which the claim corresponds.
    #[prost(string, tag = "8")]
    pub service_id: ::prost::alloc::string::String,
    /// The address of the application which participated in the claimed session.
    #[prost(string, tag = "9")]
    pub application_address: ::prost::alloc::string::String,
    /// The end block height of the session to which the claim corresponds.
    #[prost(int64, tag = "10")]
    pub session_end_block_height: i64,
    /// The validation status of the claim.
    /// DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    /// enum to minimize onchain disk utilization. This is necessary because event
    /// data is not always protobuf-encoded in the various places and formats that it
    /// appears in onchain leveldb databases.
    /// Enum values:
    /// PENDING_VALIDATION = 0;
    /// VALIDATED = 1;
    /// INVALID = 2;
    #[prost(int32, tag = "11")]
    pub claim_proof_status_int: i32,
    /// The operator address of the supplier whose claim expired.
    #[prost(string, tag = "12")]
    pub supplier_operator_address: ::prost::alloc::string::String,
}
/// EventClaimSettled is emitted during settlement whenever a claim is successfully settled.
/// It may or may not require a proof depending on various on-chain parameters and other factors.
///
/// Next index: 24
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventClaimSettled {
    /// Whether a proof was required for the claim to be settled.
    /// DEV_NOTE: This field uses the integer representation of the ProofRequirementReason
    /// enum to minimize onchain disk utilization. This is necessary because event
    /// data is not always protobuf-encoded in the various places and formats that it
    /// appears in onchain leveldb databases.
    /// Enum values:
    /// NOT_REQUIRED = 0;
    /// PROBABILISTIC = 1;
    /// THRESHOLD = 2;
    #[prost(int32, tag = "2")]
    pub proof_requirement_int: i32,
    /// Number of relays claimed to be in the session tree.
    #[prost(uint64, tag = "3")]
    pub num_relays: u64,
    /// Number of compute units claimed in the session tree.
    /// It is a function of the number of relays in the session tree and onchain parameters.
    #[prost(uint64, tag = "4")]
    pub num_claimed_compute_units: u64,
    /// Number of estimated compute units claimed in the session tree.
    /// It is a function of the number of claimed compute units and the relay difficulty multiplier for the particular service.
    #[prost(uint64, tag = "5")]
    pub num_estimated_compute_units: u64,
    /// The uPOKT coin claimed to be rewarded for the work done as a function of
    /// the number of estimated compute units and the compute units to token multiplier.
    #[prost(string, tag = "8")]
    pub claimed_upokt: ::prost::alloc::string::String,
    /// The Service ID to which the claim corresponds.
    #[prost(string, tag = "9")]
    pub service_id: ::prost::alloc::string::String,
    /// The address of the application which participated in the claimed session.
    #[prost(string, tag = "10")]
    pub application_address: ::prost::alloc::string::String,
    /// The end block height of the session to which the claim corresponds.
    #[prost(int64, tag = "11")]
    pub session_end_block_height: i64,
    /// The validation status of the claim.
    /// DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    /// enum to minimize onchain disk utilization. This is necessary because event
    /// data is not always protobuf-encoded in the various places and formats that it
    /// appears in onchain leveldb databases.
    /// Enum values:
    /// PENDING_VALIDATION = 0;
    /// VALIDATED = 1;
    /// INVALID = 2;
    #[prost(int32, tag = "12")]
    pub claim_proof_status_int: i32,
    /// The operator address of the supplier who submitted the claim.
    #[prost(string, tag = "13")]
    pub supplier_operator_address: ::prost::alloc::string::String,
    /// A map of addresses to token amounts corresponding to the distribution of the reward tokens.
    /// Deprecated: Use reward_distribution_detailed which preserves OpReason per entry.
    #[prost(map = "string, string", tag = "14")]
    pub reward_distribution: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Detailed per-reason reward breakdown. Unlike reward_distribution (field 14)
    /// which merges all reasons per address, this preserves the OpReason for each entry.
    #[prost(message, repeated, tag = "15")]
    pub reward_distribution_detailed: ::prost::alloc::vec::Vec<RewardDistributionDetail>,
    /// The actual settlement amount after overservicing cap, before mint_ratio.
    /// Indexers can compute: overservicing_loss = claimed_upokt - settled_upokt
    #[prost(string, tag = "16")]
    pub settled_upokt: ::prost::alloc::string::String,
    /// The mint_ratio applied during settlement (from tokenomics params).
    /// Indexers can compute: deflation_loss = settled_upokt * (1 - mint_ratio)
    #[prost(string, tag = "17")]
    pub mint_ratio: ::prost::alloc::string::String,
    /// The unique session ID hash for this claim's session.
    /// Enables direct joins without needing composite keys (app + service + session_end).
    #[prost(string, tag = "18")]
    pub session_id: ::prost::alloc::string::String,
    /// The owner address of the supplier who submitted the claim.
    /// Useful when owner != operator (delegated staking) for attributing rewards.
    #[prost(string, tag = "19")]
    pub supplier_owner_address: ::prost::alloc::string::String,
    /// The probabilistic estimation of the total number of relays served in this session.
    /// Derived from the relay mining difficulty: num_estimated_relays = num_relays * difficulty_multiplier.
    /// Unlike num_relays (which is only the count of leaves in the session tree that matched
    /// the relay mining difficulty), this reflects the actual estimated workload.
    #[prost(uint64, tag = "20")]
    pub num_estimated_relays: u64,
    /// The actual amount of uPOKT minted for this claim via the Relay Burn Equals Mint TLM.
    /// minted_upokt = settled_upokt * mint_ratio (truncated to integer).
    /// This is the real economic value created by this claim after both overservicing and deflation.
    /// Relationship: claimed_upokt >= settled_upokt >= minted_upokt
    #[prost(string, tag = "21")]
    pub minted_upokt: ::prost::alloc::string::String,
    /// The amount of uPOKT lost to overservicing for this claim.
    /// overservicing_loss_upokt = claimed_upokt - settled_upokt.
    /// Zero when the supplier's claim fits within the application's per-supplier budget.
    #[prost(string, tag = "22")]
    pub overservicing_loss_upokt: ::prost::alloc::string::String,
    /// The amount of uPOKT permanently removed from circulation (deflation) for this claim.
    /// deflation_loss_upokt = settled_upokt - minted_upokt = settled_upokt * (1 - mint_ratio).
    /// Zero when mint_ratio = 1 (no deflation).
    #[prost(string, tag = "23")]
    pub deflation_loss_upokt: ::prost::alloc::string::String,
}
/// EventApplicationOverserviced is emitted when an Application's stake cannot cover the Supplier's claim.
/// This means the following will ALWAYS be strictly true:  effective_burn \< expected_burn
///
/// * Number of tokens burnt from app stake \< Number of tokens burnt from supplier stake
///
/// Next index: 10
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventApplicationOverserviced {
    /// The application address consuming onchain services
    #[prost(string, tag = "1")]
    pub application_addr: ::prost::alloc::string::String,
    /// The supplier operator address providing onchain services
    #[prost(string, tag = "2")]
    pub supplier_operator_addr: ::prost::alloc::string::String,
    /// Expected number of tokens to be burnt from the application's stake.
    /// A function of the actual amount of work claimed to be done.
    #[prost(string, tag = "5")]
    pub expected_burn: ::prost::alloc::string::String,
    /// Actual number of tokens burnt from the application's stake.
    /// A function of the amount that could be covered (less than) relative to the amount of work claimed to be done.
    #[prost(string, tag = "6")]
    pub effective_burn: ::prost::alloc::string::String,
    /// The Service ID for the session where overservicing occurred.
    /// Enables unambiguous joins with EventClaimSettled.
    #[prost(string, tag = "7")]
    pub service_id: ::prost::alloc::string::String,
    /// The session end block height where overservicing occurred.
    /// Together with service_id, application_addr, and supplier_operator_addr,
    /// this uniquely identifies the corresponding EventClaimSettled.
    #[prost(int64, tag = "8")]
    pub session_end_block_height: i64,
    /// Whether overservicing was triggered by per_session_spend_limit (true)
    /// vs the standard stake-based cap (false, default).
    #[prost(bool, tag = "9")]
    pub spend_limit_exceeded: bool,
}
/// EventSupplierSlashed is emitted when a supplier is slashed.
/// This can happen for in cases such as missing or invalid proofs for submitted claims.
///
/// Next index: 9
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventSupplierSlashed {
    /// Amount slashed from the supplier's stake.
    /// A function of the claim size, supplier stake, and various onchain parameters.
    #[prost(string, tag = "3")]
    pub proof_missing_penalty: ::prost::alloc::string::String,
    /// The Service ID to which the claim corresponds.
    #[prost(string, tag = "4")]
    pub service_id: ::prost::alloc::string::String,
    /// The address of the application which participated in the claimed session.
    #[prost(string, tag = "5")]
    pub application_address: ::prost::alloc::string::String,
    /// The end block height of the session to which the claim corresponds.
    #[prost(int64, tag = "6")]
    pub session_end_block_height: i64,
    /// The validation status of the claim.
    /// DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    /// enum to minimize onchain disk utilization. This is necessary because event
    /// data is not always protobuf-encoded in the various places and formats that it
    /// appears in onchain leveldb databases.
    /// Enum values:
    /// PENDING_VALIDATION = 0;
    /// VALIDATED = 1;
    /// INVALID = 2;
    #[prost(int32, tag = "7")]
    pub claim_proof_status_int: i32,
    /// The operator address of the supplier that was slashed.
    #[prost(string, tag = "8")]
    pub supplier_operator_address: ::prost::alloc::string::String,
}
/// EventClaimDiscarded is emitted when a claim is discarded due to unexpected situations.
/// It is used to prevent chain halts in favor of some missing claims.
///
/// Next index: 8
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventClaimDiscarded {
    /// The error that caused the claim to be discarded.
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    /// The Service ID to which the claim corresponds.
    #[prost(string, tag = "3")]
    pub service_id: ::prost::alloc::string::String,
    /// The address of the application which participated in the claimed session.
    #[prost(string, tag = "4")]
    pub application_address: ::prost::alloc::string::String,
    /// The end block height of the session to which the claim corresponds.
    #[prost(int64, tag = "5")]
    pub session_end_block_height: i64,
    /// The validation status of the claim.
    /// DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    /// enum to minimize onchain disk utilization. This is necessary because event
    /// data is not always protobuf-encoded in the various places and formats that it
    /// appears in onchain leveldb databases.
    /// Enum values:
    /// PENDING_VALIDATION = 0;
    /// VALIDATED = 1;
    /// INVALID = 2;
    #[prost(int32, tag = "6")]
    pub claim_proof_status_int: i32,
    /// The operator address of the supplier whose claim was discarded.
    #[prost(string, tag = "7")]
    pub supplier_operator_address: ::prost::alloc::string::String,
}
/// RewardDistributionDetail is a per-recipient, per-reason reward breakdown for a single claim.
/// Unlike the reward_distribution map (which merges all OpReasons per address),
/// this preserves the OpReason for each entry.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RewardDistributionDetail {
    /// The recipient address (bech32).
    #[prost(string, tag = "1")]
    pub recipient_address: ::prost::alloc::string::String,
    /// The settlement operation reason from the TLM.
    #[prost(enumeration = "SettlementOpReason", tag = "2")]
    pub op_reason: i32,
    /// The reward amount as a coin string (e.g. "1000upokt").
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
}
/// EventSettlementBatch is emitted once per unique aggregated bank operation during settlement.
/// It provides the link between batched bank transfers and the settlement context.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventSettlementBatch {
    /// The session end block height for the batch of settlements.
    #[prost(int64, tag = "1")]
    pub session_end_block_height: i64,
    /// The sender module account (or destination module for mints/burns).
    #[prost(string, tag = "2")]
    pub sender_module: ::prost::alloc::string::String,
    /// The recipient (bech32 address for mod-to-acct, module name for mod-to-mod, empty for mints/burns).
    #[prost(string, tag = "3")]
    pub recipient: ::prost::alloc::string::String,
    /// The settlement operation reason from the TLM.
    #[prost(enumeration = "SettlementOpReason", tag = "4")]
    pub op_reason: i32,
    /// The total aggregated amount as a coin string.
    #[prost(string, tag = "5")]
    pub total_amount: ::prost::alloc::string::String,
    /// Number of individual claims that contributed to this batch.
    #[prost(uint32, tag = "6")]
    pub num_claims: u32,
    /// The type of bank operation: "mint", "burn", "mod_to_mod", "mod_to_acct".
    #[prost(string, tag = "7")]
    pub op_type: ::prost::alloc::string::String,
}
/// EventApplicationReimbursementRequest is emitted when an application requests a reimbursement from the DAO.
/// It is intended to prevent self dealing attacks when global inflation is enabled.
/// TODO_DISTANT_FUTURE: Remove this once global inflation is disabled in perpetuity.
///
/// Next index: 8
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EventApplicationReimbursementRequest {
    /// The application address consuming onchain services requesting reimbursement.
    #[prost(string, tag = "1")]
    pub application_addr: ::prost::alloc::string::String,
    /// The supplier operator address providing onchain services
    #[prost(string, tag = "2")]
    pub supplier_operator_addr: ::prost::alloc::string::String,
    /// The supplier owner address providing onchain services
    #[prost(string, tag = "3")]
    pub supplier_owner_addr: ::prost::alloc::string::String,
    /// The service ID associated with the session where a claim was submitted.
    #[prost(string, tag = "4")]
    pub service_id: ::prost::alloc::string::String,
    /// The session ID associated with the session where a claim was submitted.
    #[prost(string, tag = "5")]
    pub session_id: ::prost::alloc::string::String,
    /// The amount of uPOKT to be reimbursed to the application.
    #[prost(string, tag = "7")]
    pub amount: ::prost::alloc::string::String,
}
/// TODO_CONSIDERATION: Consider prefixing these enums with CLAIM_EXPIRATION_REASON\_
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClaimExpirationReason {
    /// Default value, means may be valid
    ExpirationReasonUnspecified = 0,
    /// A proof was required but not submitted
    ProofMissing = 1,
    /// A proof was submitted but was invalid
    ProofInvalid = 2,
}
impl ClaimExpirationReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ExpirationReasonUnspecified => "EXPIRATION_REASON_UNSPECIFIED",
            Self::ProofMissing => "PROOF_MISSING",
            Self::ProofInvalid => "PROOF_INVALID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXPIRATION_REASON_UNSPECIFIED" => Some(Self::ExpirationReasonUnspecified),
            "PROOF_MISSING" => Some(Self::ProofMissing),
            "PROOF_INVALID" => Some(Self::ProofInvalid),
            _ => None,
        }
    }
}
/// Params defines the parameters for the tokenomics module.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Params {
    /// dao_reward_address is where the DAO's portion of claims submitted are distributed.
    ///
    /// Bech32 cosmos address
    #[prost(string, tag = "6")]
    pub dao_reward_address: ::prost::alloc::string::String,
    /// mint_allocation_percentages represents the distribution of newly minted tokens.
    /// GlobalMintTLM: Only used by the GlobalMintTLM at the end of claim settlement.
    #[prost(message, optional, tag = "1")]
    pub mint_allocation_percentages: ::core::option::Option<MintAllocationPercentages>,
    /// global_inflation_per_claim is the percentage of a claim's claimable uPOKT amount to be minted on settlement.
    /// GlobalMintTLM: Only used by the GlobalMintTLM at the end of claim settlement.
    #[prost(double, tag = "7")]
    pub global_inflation_per_claim: f64,
    /// mint_equals_burn_claim_distribution controls how the settlement amount is distributed
    /// when global inflation is disabled (global_inflation_per_claim = 0).
    /// MintEqualsBurnTLM: Only used by the MintEqualsBurnTLM at the end of claim settlement.
    #[prost(message, optional, tag = "8")]
    pub mint_equals_burn_claim_distribution: ::core::option::Option<
        MintEqualsBurnClaimDistribution,
    >,
    /// mint_ratio is the proportion of burned tokens to mint (0.0 \< mint_ratio \<= 1.0).
    /// PIP-41: A value of 0.975 means 97.5% of burned tokens are minted, 2.5% permanently removed.
    /// MintEqualsBurnTLM: Only used by the MintEqualsBurnTLM at the end of claim settlement.
    /// Default: 1.0 (no deflation - mint equals burn for backward compatibility)
    #[prost(double, tag = "9")]
    pub mint_ratio: f64,
}
/// MintAllocationPercentages captures the distribution of newly minted tokens.
/// The sum of all new tokens minted must equal 1.
/// GlobalMintTLM: Only used by the GlobalMintTLM at the end of claim settlement.
/// TODO_DISTANT_FUTURE: Remove this once global inflation is disabled in perpetuity.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MintAllocationPercentages {
    /// dao - % of newley minted tokens sent to the DAO reward address.
    #[prost(double, tag = "1")]
    pub dao: f64,
    /// proposer - % of newley minted tokens sent to the block proposer (i.e. validator0 account address.
    #[prost(double, tag = "2")]
    pub proposer: f64,
    /// supplier - % of newley minted tokens sent to the block supplier account address.
    #[prost(double, tag = "3")]
    pub supplier: f64,
    /// source_owner - % of newley minted tokens sent to the service source owner account address.
    #[prost(double, tag = "4")]
    pub source_owner: f64,
    /// application - % of newley minted tokens sent to the application account address.
    #[prost(double, tag = "5")]
    pub application: f64,
}
/// MintEqualsBurnClaimDistribution captures the distribution of claimable tokens.
/// The sum of all tokens being burnt from the application's stake must equal 1.
/// GlobalMintEqualsBurnTLM: Only used by the GlobalMintEqualsBurnTLM at the end of claim settlement.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MintEqualsBurnClaimDistribution {
    /// dao - % of claimable tokens sent to the DAO reward address.
    #[prost(double, tag = "1")]
    pub dao: f64,
    /// TODO_TECHDEBT: Rename "proposer" to "validators" to reflect the work done in #1753.
    /// This will span all references to the term "proposer" across documentation, functions, protobufs, variables, tooling, etc..
    ///
    /// proposer - % of claimable tokens sent to the block proposer (i.e. validator0) account address.
    #[prost(double, tag = "2")]
    pub proposer: f64,
    /// supplier - % of claimable tokens sent to the block supplier account address.
    #[prost(double, tag = "3")]
    pub supplier: f64,
    /// source_owner - % of claimable tokens sent to the service source owner account address.
    #[prost(double, tag = "4")]
    pub source_owner: f64,
    /// application - % of claimable tokens sent to the application account address.
    #[prost(double, tag = "5")]
    pub application: f64,
}
/// GenesisState defines the tokenomics module's genesis state.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    /// params defines all the parameters of the module.
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
}
/// QueryParamsRequest is request type for the Query/Params RPC method.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryParamsRequest {}
/// QueryParamsResponse is response type for the Query/Params RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    /// params holds all the parameters of this module.
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
}
/// Generated client implementations.
pub mod query_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Query defines the gRPC querier service.
    #[derive(Debug, Clone)]
    pub struct QueryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl QueryClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QueryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            QueryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Parameters queries the parameters of the module.
        pub async fn params(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryParamsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryParamsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.tokenomics.Query/Params",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.tokenomics.Query", "Params"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// MsgUpdateParams is the Msg/UpdateParams request type to update all params at once.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateParams {
    /// authority is the address that controls the module (defaults to x/gov unless overwritten).
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
    /// params defines the tokenomics parameters to update.
    #[prost(message, optional, tag = "2")]
    pub params: ::core::option::Option<Params>,
}
/// MsgUpdateParamsResponse defines the response structure for executing a MsgUpdateParams message.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MsgUpdateParamsResponse {}
/// MsgUpdateParam is the Msg/UpdateParam request type to update a single param.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateParam {
    /// authority is the address that controls the module (defaults to x/gov unless overwritten).
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
    /// The (name, as_type) tuple must match the corresponding name and type as specified in the `Params` message in `proof/params.proto.`
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(oneof = "msg_update_param::AsType", tags = "3, 4, 5, 6")]
    pub as_type: ::core::option::Option<msg_update_param::AsType>,
}
/// Nested message and enum types in `MsgUpdateParam`.
pub mod msg_update_param {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum AsType {
        #[prost(message, tag = "3")]
        AsMintAllocationPercentages(super::MintAllocationPercentages),
        #[prost(string, tag = "4")]
        AsString(::prost::alloc::string::String),
        #[prost(double, tag = "5")]
        AsFloat(f64),
        #[prost(message, tag = "6")]
        AsMintEqualsBurnClaimDistribution(super::MintEqualsBurnClaimDistribution),
    }
}
/// MsgUpdateParamResponse defines the response structure for executing a MsgUpdateParam message after a single param update.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MsgUpdateParamResponse {}
/// Generated client implementations.
pub mod msg_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Msg defines the Msg service.
    #[derive(Debug, Clone)]
    pub struct MsgClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MsgClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MsgClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MsgClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MsgClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// UpdateParams defines a (governance) operation for updating the module
        /// parameters. The authority defaults to the x/gov module account.
        pub async fn update_params(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUpdateParams>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateParamsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.tokenomics.Msg/UpdateParams",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.tokenomics.Msg", "UpdateParams"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_param(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUpdateParam>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateParamResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pocket.tokenomics.Msg/UpdateParam",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pocket.tokenomics.Msg", "UpdateParam"));
            self.inner.unary(req, path, codec).await
        }
    }
}
