[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
shannon-protos = { path = "../shannon-protos" }
tonic = {version = "0.13", features = ["transport","tls-native-roots"]}
tokio = {version = "1.45.0", features = ["macros", "rt-multi-thread"]}
